"""Structured output model for the query generation step."""

from typing import List

from pydantic import BaseModel, Field


class QueryList(BaseModel):
    """Structured output model for the query generation step.

    Used with ``llm.with_structured_output()`` to constrain the LLM
    to return a list of search queries.

    Attributes:
        queries: List of search queries generated by the LLM.
    """

    queries: List[str] = Field(default_factory=list, description="List of search queries")
